# 1 导入numpy库

In [1]:
import numpy as np

# 2 打印numpy的版本和配置说明

In [2]:
print(np.__version__)
np.show_config()

1.16.4
openblas_info:
    language = f77
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    define_macros = [('HAVE_CBLAS', None)]
openblas_lapack_info:
    language = f77
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    language = f77
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    language = f77
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    define_macros = [('HAVE_CBLAS', None)]


# 3 创建一个长度为10的空向量

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 4 找到任何一个数组的内存大小 

In [4]:
A = np.zeros((2,2))
print(A.size * A.itemsize)

32


# 5 从命令行得到numpy中add函数的说明文档 

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

# 6 创建一个长度为10并且除了第五个值为1的空向量

In [6]:
B = np.zeros(10)
B[4] = 1
B

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 7 创建一个值域范围从10到49的向量

In [7]:
C = np.arange(10,50)
C

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 8 反转一个向量

In [8]:
C = C[::-1]
C

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

# 9  创建一个 3x3 并且值从0到8的矩阵

In [9]:
D = np.arange(0,9).reshape(3,3)
D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 10 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [10]:
E = np.nonzero([1,2,0,0,4,0])
print(E)

(array([0, 1, 4], dtype=int64),)


# 11 创建一个 3x3 的单位矩阵

In [11]:
F = np.eye(3)
F

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 12 创建一个 3x3x3的随机数组

In [12]:
G = np.random.random((3,3,3))
G

array([[[0.55740791, 0.88438644, 0.71794546],
        [0.11437944, 0.02846456, 0.26764023],
        [0.74090784, 0.31376508, 0.0766003 ]],

       [[0.25100334, 0.71167484, 0.98772726],
        [0.21059534, 0.01740553, 0.27794325],
        [0.94315911, 0.97406161, 0.66012647]],

       [[0.10928816, 0.43598201, 0.87391324],
        [0.33220902, 0.91543693, 0.64154887],
        [0.04725696, 0.92061446, 0.99919404]]])

# 13 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [13]:
H = np.random.random((10,10))
maximum,minimum = H.max() , H.min()
print(maximum,minimum)

0.9773821478318022 0.0068528402713442516


# 14 创建一个长度为30的随机向量并找到它的平均值

In [14]:
I = np.random.random(30)
print(I.mean())

0.48923615440437673


# 15 创建一个二维数组，其中边界值为1，其余值为0

In [15]:
K = np.ones((10,10))
K[1:-1,1:-1] = 0
K

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 16 对于一个存在在数组，如何添加一个用0填充的边界

In [16]:
L = np.ones((5,5))
L = np.pad(L,pad_width=1,mode='constant',constant_values=0)
L
# #np.pad(array,pad_width,mode,kwargs)
# array——表示需要填充的数组，pad_width——表示每个轴边缘需要填充的数值数目 mode——表示填充的方式

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 17 以下表达式运行的结果分别是什么

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


# 18 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [18]:
M = np.diag(1+np.arange(4),k=-1)
M

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 19 创建一个8x8 的矩阵，并且设置成棋盘样式

In [19]:
N = np.zeros((8,8),dtype=int)
N[1::2,::2] = 1
N[::2,1::2] = 1
N

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 20 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [20]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


# 21 用tile函数去创建一个 8x8的棋盘样式矩阵

In [21]:
O = np.tile( np.array([[0,1],[1,0]]), (4,4))
O
# numpy.tile(A,reps)
# tile共有2个参数，A指待输入数组，reps则决定A重复的次数。

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 22 对一个5x5的随机矩阵做归一化

In [22]:
P = np.random.random((5,5))
Pmax, Pmin = P.max(), P.min()
P = (P - Pmin)/(Pmax - Pmin)
P

array([[0.85240564, 0.8863727 , 0.75883927, 0.        , 0.72616656],
       [0.55470787, 0.98427744, 0.88246622, 1.        , 0.13091606],
       [0.7975391 , 0.03750529, 0.78663885, 0.16132898, 0.56555441],
       [0.48359705, 0.81196275, 0.22181481, 0.55017889, 0.5061172 ],
       [0.84834687, 0.4302038 , 0.14200837, 0.14117478, 0.52426148]])

# 23 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype

In [23]:
color = np.dtype([("r",np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

# 24 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积

In [24]:
Q = np.dot(np.ones((5,3)),np.ones((3,2)))
Q

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

# 25 给定一个一维数组，对其在3到8之间的所有元素取反

In [25]:
R = np.arange(10)
R[(3 < R) & (R <= 8)] *= -1
R

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9])

# 26 下面脚本运行后的结果是什么

In [26]:
print(sum(range(5),-1))
# 0到4所有元素加起来再减1
from numpy import *
print(sum(range(5),-1))
# 0到4所有元素相加，
# np.sum的求和相当于对矩阵进行压缩
# 第一个参数是要参与求和压缩的变量：向量/数组/矩阵。
# 第二个则决定求和的方式：1.None，2.整数， 3.整数元组。有这三种方式
# 1.当求和方式为none,相当于把所有元素加成一个数
# 2.当求和方式为整数时，相当于选择一个轴向进行相加，简单的说：压缩行还是压缩

9
10


# 27 考虑一个整数向量Z,下列表达合法的是哪个? 


###### Z**Z

###### 2 << Z >> 2

###### Z <- Z

###### 1j*Z

###### Z/1/1

###### Z < Z > Z
    

In [27]:
Z = np.arange(5)
print(Z ** Z) 

[  1   1   4  27 256]


In [28]:
print(2 << Z >> 2 )

[0 1 2 4 8]


In [29]:
Z <- Z 

array([False, False, False, False, False])

In [30]:
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [31]:
Z/1/1

array([0., 1., 2., 3., 4.])

In [32]:
Z < Z > Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# 28 表达式结果

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


d:\anaconda3\envs\py35\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
d:\anaconda3\envs\py35\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


# 29  如何从零位对浮点数组做舍入

In [34]:
S = np.random.uniform(-10,+10,10)# np.random.uniform(low上界,high下界,size输出样本数目)
print(np.copysign(np.ceil(np.abs(S)),S))

[  4. -10.  10.   7.   2.  -6.  -1.  -6.   9.   5.]


# 30  如何找到两个数组中的共同元素

In [35]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(np.intersect1d(a1,a2))

[1 4 5 6 7]


# 31 如何忽略所有的 numpy 警告

In [36]:
#Suicide mode on
defaults = np.ones(1) / 0
#Back to sanity
_ = np.seterr(**defaults)
An equivalent way, with a context manager:
with np.errstate(divide='ignore'):
        z = np.ones(1)/0

SyntaxError: invalid syntax (<ipython-input-36-795d9013c52b>, line 5)

# 32 

In [37]:
np.sqrt(-1) == np.emath.sqrt(-1)

d:\anaconda3\envs\py35\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

# 33  如何得到昨天，今天，明天的日期?

In [38]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-07
Today is 2019-08-08
Tomorrow is 2019-08-09


# 34 如何得到所有与2016年7月对应的日期？

In [39]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


# 35 如何直接在位计算(A+B)*(-A/2)(不建立副本)?

In [40]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

# 36 用五种不同的方法去提取一个随机数组的整数部分

In [41]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[1. 4. 9. 8. 3. 0. 8. 0. 7. 8.]
[1. 4. 9. 8. 3. 0. 8. 0. 7. 8.]
[1. 4. 9. 8. 3. 0. 8. 0. 7. 8.]
[1 4 9 8 3 0 8 0 7 8]
[1. 4. 9. 8. 3. 0. 8. 0. 7. 8.]


# 37 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [42]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 38 通过考虑一个可生成10个整数的函数，来构建一个数组

In [43]:
def generate():
    for x in range(10):
        yield x
d = np.fromiter(generate(),dtype=float,count=-1)
print(d)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# 39 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [44]:
f = np.linspace(0,1,11,endpoint=False)[1:]#在0和1之间划分为11份
print(f)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# 40 创建一个长度为10的随机向量，并将其排序

In [45]:
a = np.random.random(10)
a.sort()
print(a)

[0.05848921 0.11844981 0.20288087 0.36712988 0.4247941  0.44450274
 0.55387654 0.66378835 0.68680837 0.78894682]


# 41 对于一个小数组，如何用比 np.sum更快的方式对其求和？

In [46]:
a = np.arange(10)
np.add.reduce(a)

45

# 42 对于两个随机数组A和B，检查它们是否相等

In [47]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equal = np.allclose(a,b)
print(equal)

False


# 43 创建一个只读数组(read-only) 

In [48]:
w = np.zeros(10)
w.flags.writeable = False
w[0] = 1

ValueError: assignment destination is read-only

# 44 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [49]:
a = np.random.random((10,2))
X,Y = a[:,0],a[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.78034682 0.80445939 0.56023881 0.83186601 0.82843815 0.46451469
 0.82438864 0.37356105 1.17678531 0.38430109]
[1.36533819 0.42272053 0.33082223 0.49401243 0.05537553 0.99459991
 0.61288165 1.43631867 0.58371607 1.34988079]


# 45 创建一个长度为10的向量，并将向量中最大值替换为1

In [50]:
s = np.random.random(10)
s[s.argmax()] = 1
print(s)

[0.70857846 0.82452524 0.39608301 0.05776933 0.39718733 0.16386511
 0.63096526 0.70049266 1.         0.33688064]


# 46 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

In [51]:
z = np.zeros((5,6),[('x',float),('y',float)])
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,6),
                            np.linspace(0,1,5))
print(z)

[[(0. , 0.  ) (0.2, 0.  ) (0.4, 0.  ) (0.6, 0.  ) (0.8, 0.  ) (1. , 0.  )]
 [(0. , 0.25) (0.2, 0.25) (0.4, 0.25) (0.6, 0.25) (0.8, 0.25) (1. , 0.25)]
 [(0. , 0.5 ) (0.2, 0.5 ) (0.4, 0.5 ) (0.6, 0.5 ) (0.8, 0.5 ) (1. , 0.5 )]
 [(0. , 0.75) (0.2, 0.75) (0.4, 0.75) (0.6, 0.75) (0.8, 0.75) (1. , 0.75)]
 [(0. , 1.  ) (0.2, 1.  ) (0.4, 1.  ) (0.6, 1.  ) (0.8, 1.  ) (1. , 1.  )]]


# 47 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [52]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


# 48 打印每个numpy标量类型的最小值和最大值？

In [53]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


# 49 如何打印一个数组中的所有数值?

In [54]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

# 50 给定标量时，如何找到数组中最接近标量的值？

In [55]:
z = np.arange(100)
a = np.random.uniform(0,100)
index = (np.abs(z-a).argmin())
print(z[index])

68
